# Generated by Django 4.2.7 on 2023-11-24 18:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('esporte', '0001_initial'),
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='esporte',
        ),
        migrations.AlterField(
            model_name='evento',
            name='id_participantes',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evento',
            name='esporte',
            field=models.ManyToManyField(to='esporte.esporte'),
        ),
    ]
