# Generated by Django 4.2.7 on 2023-11-24 18:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evento', '0002_remove_evento_esporte_alter_evento_id_participantes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='id_participantes',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
