# Generated by Django 4.2.7 on 2023-11-25 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evento', '0003_alter_evento_id_participantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='criador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='criador', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
