version: '3.8'

services:
  back:
    build: api/sportbuddyapi
    depends_on:
      - postgres
      - redis
    ports:
      - 8000:8000
  
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  redis:
    image: redis:7
    ports:
      - 6379:6379

volumes:
  postgres-data: {}