# Generated by Django 4.2.7 on 2023-11-24 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_amizade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ignorar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ignorado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_ignorado', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_que_ignora', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
