# Generated by Django 4.2.7 on 2023-11-25 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_ignorar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('amizade', 'amizade'), ('evento', 'evento')], default='amizade', max_length=200)),
                ('notificacao', models.CharField(max_length=200)),
                ('lida', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_notificado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
