# Generated by Django 4.2.7 on 2023-11-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_notificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('friend_req', 'friend_req'), ('evento', 'evento'), ('req_update', 'req_update')], default='amizade', max_length=200),
        ),
    ]
