# Generated by Django 4.2.7 on 2023-11-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_alter_notificacao_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificacao',
            old_name='notificacao',
            new_name='description',
        ),
        migrations.AddField(
            model_name='notificacao',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
