# Generated by Django 4.2.7 on 2023-11-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_rename_notificacao_notificacao_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='image',
            field=models.CharField(blank=True, default='https://lorempicsum.com/200/200/', max_length=200, null=True),
        ),
    ]
