# Generated by Django 4.2.7 on 2023-11-25 12:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0012_notificacao_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
