# Generated by Django 4.2.7 on 2023-11-25 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0003_alter_evento_id_participantes'),
        ('usuario', '0013_notificacao_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='evento_relacionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evento_relacionado', to='evento.evento'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='usuario_relacionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_relacionado', to=settings.AUTH_USER_MODEL),
        ),
    ]
