# Generated by Django 4.2.7 on 2023-11-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferencia',
            name='local_preferencia',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
